version: "3.8"

services:

  series_directus:
    image: "directus/directus:latest"
    container_name: "geoquizz_directus"
    env_file:
      - .env
    ports:
      - "8055:8055"
    depends_on:
      - series_postgres
    networks:
      - geoquizz_net

  series_postgres:
    image: "postgres:latest"
    container_name: "geoquizz_postgres"
    env_file:
      - .env
    volumes:
      - ./data-series:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - geoquizz_net

 # geoquizz_slim:
  #  build:
 #     context: .
 #     dockerfile: Dockerfile
 #   container_name: "geoquizz_slim"
 #   env_file:
 #     - .env
 #   ports:
  #    - "8080:8080"
  #  depends_on:
  #  - geoquizz_postgres
  #  networks:
  #    - geoquizz_net

  #geoquizz_postgres:
  #  image: "postgres:latest"
  #  container_name: "geoquizz_postgres"
  #  env_file:
  #    - .env
  #  volumes:
  #    - ./data:/var/lib/postgresql/data
  #  ports:
  #    - "5432:5432"
   # networks:
   #   - geoquizz_net

  auth_slim:
    image: "canals/php:8.2"
    container_name: "auth_slim"
    env_file:
      - .env
    ports:
      - "8081:80"
    volumes:
      - ./auth_geoquizz/public:/var/www/html
      - ./auth_geoquizz:/var/www
    working_dir: /var/www
    depends_on:
      - auth_postgres
    networks:
      - geoquizz_net

  auth_postgres:
    image: "postgres:latest"
    container_name: "auth_postgres"
    env_file:
      - .env
    volumes:
      - ./data-auth:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - geoquizz_net

  #websocket_node:
  #  build:
   #   context: .
  #    dockerfile: Dockerfile
  #  container_name: "websocket_node"
  #  env_file:
  #   - .env
  #  ports:
  #    - "8082:8082"
  #  depends_on:
  #    - geoquizz_postgres
  #  networks:
  #    - geoquizz_net

  #rabbitmq:
  #  image: "rabbitmq:3-management"
  #  container_name: "rabbitmq"
  #  ports:
  #    - "15672:15672"
  #  - "5672:5672"
  #  networks:
  #    - geoquizz_net

  #front_vue:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: "front_vue"
  #  env_file:
  #    - .env
  #  ports:
  #    - "8083:8083"
  #  networks:
  #    - geoquizz_net

  gateway_nginx:
    build:
      context: gateway_nginx
      dockerfile: Dockerfile
    container_name: "gateway_nginx"
    env_file:
      - .env
    ports:
      - "8084:8084"
    networks:
      - geoquizz_net
    volumes:
      - ./gateway_nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway_nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - auth_slim

networks:
  geoquizz_net:
    driver: bridge