version: "3.8"

services:

  adminer:
    image: "adminer:latest"
    container_name: "geoquizz-adminer"
    ports:
      - "8085:8080"
    networks:
      - geoquizz_net

  series_directus:
    image: "directus/directus:latest"
    container_name: "series_directus"
    env_file:
      - series.env
    ports:
      - "8055:8055"
    depends_on:
      - series_postgres
    networks:
      - geoquizz_net

  series_postgres:
    image: "postgres:latest"
    container_name: "series_postgres"
    env_file:
      - series.env
    volumes:
      - ./data-series:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - geoquizz_net

  service_geoquizz:
    image: "canals/php:8.2"
    container_name: "service_geoquizz"
    ports:
      - '2082:80'
      - '2444:443'
    env_file:
      - geoquizz.env
    volumes:
      - ./service_geoquizz/public:/var/www/html
      - ./service_geoquizz:/var/www
    working_dir: /var/www
    depends_on:
      - service_geoquizz_postgres
    networks:
      - geoquizz_net

  service_geoquizz_postgres:
    image: "postgres:latest"
    container_name: "service_geoquizz_postgres"
    env_file:
      - geoquizz.env
    volumes:
      - ./data-service-geoquizz:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - geoquizz_net

  vue_geoquizz:
    build:
      context: vue_geoquizz
      dockerfile: Dockerfile
    container_name: "vue_geoquizz"
    ports:
      - "3001:80"
    volumes:
      - ./vue_geoquizz/dist:/usr/local/apache2/htdocs
      - /app/node_modules
    working_dir: /app
    networks:
      - geoquizz_net

  gateway_nginx:
    build:
      context: gateway_nginx
      dockerfile: Dockerfile
    container_name: "gateway_nginx"
    ports:
      - "8084:80"
    networks:
      - geoquizz_net
    volumes:
      - ./gateway_nginx/reverse.conf:/etc/nginx/conf.d/default.conf

networks:
  geoquizz_net:
    driver: bridge