version: "3.8"

services:

  adminer:
    image: "adminer:latest"
    container_name: "geoquizz-adminer"
    ports:
      - "42372:8080"
    networks:
      - geoquizz_net

  series_directus:
    image: "directus/directus:latest"
    container_name: "series_directus"
    env_file:
      - series.env
    ports:
      - "42373:8055"
    depends_on:
      - series_postgres
    networks:
      - geoquizz_net

  series_postgres:
    image: "postgres:latest"
    container_name: "series_postgres"
    env_file:
      - series.env
    volumes:
      - ./data-series:/var/lib/postgresql/data
    ports:
      - "42374:5432"
    networks:
      - geoquizz_net

  service_geoquizz:
    image: "canals/php:8.2"
    container_name: "service_geoquizz"
    ports:
      - '42375:80'
      - '42376:443'
    env_file:
      - geoquizz.env
    volumes:
      - ./service_geoquizz/public:/var/www/html
      - ./service_geoquizz:/var/www
    working_dir: /var/www
    depends_on:
      - service_geoquizz_postgres
    networks:
      - geoquizz_net

  service_geoquizz_postgres:
    image: "postgres:latest"
    container_name: "service_geoquizz_postgres"
    env_file:
      - geoquizz.env
    volumes:
      - ./data-service-geoquizz:/var/lib/postgresql/data
    ports:
      - "42377:5432"
    networks:
      - geoquizz_net

  vue_geoquizz:
    build:
      context: vue_geoquizz
      dockerfile: Dockerfile
    container_name: "vue_geoquizz"
    ports:
      - "42378:81"
    volumes:
      - ./vue_geoquizz:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - geoquizz_net
    depends_on:
      - gateway_nginx

  gateway_nginx:
    build:
      context: gateway_nginx
      dockerfile: Dockerfile
    container_name: "gateway_nginx"
    ports:
      - "42379:80"
    networks:
      - geoquizz_net
    volumes:
      - ./gateway_nginx/reverse.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service_geoquizz
      - series_directus
      - auth_geoquizz

  auth_geoquizz:
    image: "canals/php:8.2"
    container_name: "auth_geoquizz"
    env_file:
      - auth.env
    volumes:
      - ./auth_geoquizz/public:/var/www/html
      - ./auth_geoquizz:/var/www
    working_dir: /var/www
    ports:
      - "42380:80"
    depends_on:
      - auth_postgres
    networks:
      - geoquizz_net

  auth_postgres:
    image: "postgres:latest"
    container_name: "auth_postgres"
    env_file:
      - auth.env
    volumes:
      - ./data-auth:/var/lib
    networks:
      - geoquizz_net

  websocket_geoquizz:
    build:
      context: websocket_geoquizz
      dockerfile: Dockerfile
    container_name: "websocket_geoquizz"
    ports:
      - "42381:5200"
    networks:
      - geoquizz_net

networks:
  geoquizz_net:
    driver: bridge